In [4]:
import numpy as np
A = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
print(A)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [6]:
vericalsumarray=A.sum(axis=0)
print(vericalsumarray)


[ 3  6  9 12]


In [13]:
percentmatrix=A/vericalsumarray
print(percentmatrix)

[[0.33333333 0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333 0.33333333]]


In [17]:
B=np.array([1,2,3,4,5])
print(B)
C=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(C)
D=B+C
E=B/C
F=B*C
G=B-C
print("add="+str(D))
print("sub="+str(G))
print("div="+str(E))
print("mult="+str(F))

[1 2 3 4 5]
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
add=[[ 2  4  6  8 10]
 [ 2  4  6  8 10]
 [ 2  4  6  8 10]]
sub=[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
div=[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
mult=[[ 1  4  9 16 25]
 [ 1  4  9 16 25]
 [ 1  4  9 16 25]]
